language: node_js
node_js:
  - "12"

script:
  - npm test 
  - npm run build

notifications:
  email: false
  
deploy:
  provider: heroku
  app: hitch-a-ride-app
  skip_cleanup: true
  on:
    branch: main