language: node_js
node_js:
- '12'
script:
- npm test
- npm run build
notifications:
  email: false
deploy:
  provider: heroku
  app: hitch-a-ride-app
  skip_cleanup: true
  on:
    branch: main
  api_key:
    secure: GmtlCO/kIi60worCEf0D77GrhBIysQIXgvGj2jM9s/QUkmnuvKC1plbuF6BgopIk+G8Efq9KGDGuRqiaakE/Tm+Gan8lov43HH0APV1h3GP56r1G8T63vymZHKzuaT4QgnOFePywNqGA00xLP6tM0DvLDwl9vfHZHfTu0hkl/ajcDk8VKooiEL43oNsp8cjrCwuoVoVPlZt0d5z3lwv+MW/NzEwaq6VgVD5jPZTwhIJ5+48IJutaYcBQDhfnAkklsJ/JG5IGq0TUK/vYQ6aSV7ohESJ1xp8LI09LITgWZHywNgZBEsovirIKXtB6ExXQBCQQf39jpGrbMm5ABi7vqoQP/4uToAzfNnKrBekc9nqCBqglzDv5G5QOtxJrX/CAwGWa3ED5DqUDhr20vKcXq8MlqL8lolR/0k5KhOqhv63ztyHLMkerHnF+0Ylk/d3o+c4vurj2GQrzStB/95EPAklDtiI0FD4h8yXfqISWVq2N21X90O/LAuAZGQCqVgbRHfgoBnhQZJK+nA2GPTk0n3lgJ61+NBcPk+YSMkOOuszmsxzhkSGsMM2xPOE6SOvtNlypivwvR6mccgN7Nk/0AYq1ySuVy7Qc6nBAFMz907xsU2Uz9d2YkmuTkZtR0/8aKdrgXQvWCetX6Ew1WZc/6PbS3iZDDwO7hswWnM+LkKc=
